name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f0f24f772cefd677d5eae177b4fafc07681695d2a927a5edf1980e8c35c33ac"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
