name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c90926f50310b5069962f5439690b3a2ec00c71f7e880ae6c3cc38f2e6dedeeb"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
