name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75628082dcbaaab0c526c516e4e5462afa745b0f0b6b7c7810ccb3b451c39a12"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
